export const buildApiContent = {
  id: 'build-api',
  title: 'Building APIs with FastAPI: Simple Todo App',
  duration: '40 min',
  overview: `Learn to build modern, fast REST APIs in Python using FastAPI. This lesson walks you through creating a simple Todo CRUD (Create, Read, Update, Delete) API step by step.`,
  objectives: [
    'Understand FastAPI basics',
    'Define API endpoints for CRUD operations',
    'Use Pydantic models for data validation',
    'Test your API with the interactive docs',
    'Run and interact with your API locally'
  ],
  sections: [
    {
      type: 'text',
      title: 'What is FastAPI?',
      content: `FastAPI is a modern Python web framework for building APIs quickly and easily. It features automatic docs, type validation, and great performance. It is perfect for REST APIs and microservices.`
    },
    {
      type: 'code',
      title: 'Install FastAPI and Uvicorn',
      code: `# Install FastAPI and Uvicorn (ASGI server):
pip install fastapi uvicorn`
    },
    {
      type: 'text',
      content: `FastAPI is the framework. Uvicorn runs your API server. Install both before starting.`
    },
    {
      type: 'code',
      title: 'Basic FastAPI App',
      code: `from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello, FastAPI!"}`
    },
    {
      type: 'text',
      content: `This creates a FastAPI app with a single GET endpoint at '/'. It returns a simple JSON message.`
    },
    {
      type: 'code',
      title: 'Run the API Server',
      code: `# In your terminal, run:
uvicorn main:app --reload
# (Assuming your file is named main.py)`
    },
    {
      type: 'text',
      content: `Visit http://127.0.0.1:8000/docs in your browser for interactive API docs automatically generated by FastAPI.`
    },
    {
      type: 'code',
      title: 'Define a Todo Model',
      code: `from pydantic import BaseModel

class Todo(BaseModel):
    id: int
    title: str
    completed: bool = False`
    },
    {
      type: 'text',
      content: `Pydantic models define the data structure and validation for your API. Here, a Todo has an id, title, and completed status.`
    },
    {
      type: 'code',
      title: 'In-Memory Todo Storage',
      code: `todos = []  # This will store our todos as a list of Todo objects.`
    },
    {
      type: 'text',
      content: `We'll use a simple list to store todos for this example. In real apps, you'd use a database.`
    },
    {
      type: 'code',
      title: 'Create a Todo (POST)',
      code: `@app.post("/todos", response_model=Todo)
def create_todo(todo: Todo):
    todos.append(todo)
    return todo`
    },
    {
      type: 'text',
      content: `This endpoint lets you add a new todo. The request body must match the Todo model. The new todo is added to the list and returned.`
    },
    {
      type: 'code',
      title: 'Read All Todos (GET)',
      code: `@app.get("/todos", response_model=list[Todo])
def get_todos():
    return todos`
    },
    {
      type: 'text',
      content: `This endpoint returns all todos as a list. The response is validated against the Todo model.`
    },
    {
      type: 'code',
      title: 'Read a Single Todo (GET)',
      code: `@app.get("/todos/{todo_id}", response_model=Todo)
def get_todo(todo_id: int):
    for todo in todos:
        if todo.id == todo_id:
            return todo
    return {"error": "Todo not found"}`
    },
    {
      type: 'text',
      content: `This endpoint fetches a single todo by its id. If not found, it returns an error message.`
    },
    {
      type: 'code',
      title: 'Update a Todo (PUT)',
      code: `@app.put("/todos/{todo_id}", response_model=Todo)
def update_todo(todo_id: int, updated: Todo):
    for i, todo in enumerate(todos):
        if todo.id == todo_id:
            todos[i] = updated
            return updated
    return {"error": "Todo not found"}`
    },
    {
      type: 'text',
      content: `This endpoint updates a todo by id. The entire todo is replaced with the new data.`
    },
    {
      type: 'code',
      title: 'Delete a Todo (DELETE)',
      code: `@app.delete("/todos/{todo_id}")
def delete_todo(todo_id: int):
    for i, todo in enumerate(todos):
        if todo.id == todo_id:
            todos.pop(i)
            return {"message": "Todo deleted"}
    return {"error": "Todo not found"}`
    },
    {
      type: 'text',
      content: `This endpoint deletes a todo by id. It returns a message indicating success or failure.`
    },
    {
      type: 'text',
      title: 'Testing Your API',
      content: `Use the interactive docs at http://127.0.0.1:8000/docs to test all endpoints. You can create, read, update, and delete todos directly from your browser.`
    },
    {
      type: 'text',
      title: 'Key Takeaways',
      content: `- FastAPI makes it easy to build and document REST APIs
- Use Pydantic models for data validation
- Endpoints are just Python functions with decorators
- Test your API with the built-in docs
- For production, use a real database instead of a list`
    }
  ]
};
